### ISSUE TITLE
Typo in Scheduler for warmdown lr

### ISSUE THREAD

**Issue by TimZaragori** [lessw2020/Ranger22#3]
Hi, first of all thanks for making this optimizer available to all.

I think there is a typo with the warmdown of the scheduler when the type is linear. Actually the learning rate is set [line 107](https://github.com/lessw2020/Ranger22/blob/main/scheduler/scheduler22.py#L107C17-L107C77) like this: 
`group["lr"] = min(min_lr, (1 - alpha) * lr + alpha * min_lr)` which lead to this type of learning rate path
![image](https://github.com/user-attachments/assets/864b641e-d1af-40af-a4eb-db2372d6d83e)

As you can see, the warmdown starts after 720 steps and the learning rate goes straight from 1e-3 (base_lr) to 3e-5 (warmdown_min_lr) then stays at this minimum. 

I think the `min` in [line 107](https://github.com/lessw2020/Ranger22/blob/main/scheduler/scheduler22.py#L107C17-L107C77) should be replaced by `max` leading to this:
`group["lr"] = max(min_lr, (1 - alpha) * lr + alpha * min_lr)` and this type of learning rate path
![image](https://github.com/user-attachments/assets/b28a274b-29dc-4e59-b4b1-736916036acf)

It seems to me that this is what is planned in version Ranger21 ([lines 505](https://github.com/lessw2020/Ranger21/blob/main/ranger21/ranger21.py#L505C13-L509C37)).
```new_lr = self.starting_lr - reduction
if new_lr < self.min_lr:
    print(f"error in warmdown - lr below min lr. current lr = {new_lr}")
    print(f"auto handling but please report issue!")
    new_lr = self.min_lr```

**Comment by nestordemeure** [comment]
Hi Tim,

Thank you for reaching out, I believe that you are right! Could you open a PR with a fix?

Nestor
